name: logo_n_spinner
description: Flutter loader widget with logo and spinning arc. Use your image assets to create loader animation.
version: 0.1.2
homepage: https://pmatatias.dev
repository: https://github.com/pmatatias/logo-n-spinner
issue_tracker: https://github.com/pmatatias/logo-n-spinner/issues

environment:
  sdk: ">=2.14.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/flutter.png